spring:
  application:
    name: cards-service
  datasource:
    url: ${CARDS_DB_URL}
    username: ${CARDS_DB_USER}
    password: ${CARDS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka
  instance:
    instance_id: ${spring.application.name}:${spring.eureka.instance_id:${random.value}}
    prefer-ip-address: true