spring:
  application:
    name: products-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
  output:
    ansi:
      enabled: ALWAYS #Hablitando cores no console

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka
  instance:
    instance_id: ${spring.application.name}:${spring.eureka.instance_id:${random.value}}
    prefer-ip-address: true

logging:
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
